name: Integration Continue

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    routage:
        if: ${{ !contains(github.event.head_commit.message, '#code')}}
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                node-version: 18.x

            - name: Install Dep
              run: npm i

            - name: Run Main Test
              run: npm run test:file main

    deploy:
        needs: [routage]
        if: ${{ github.event_name == 'push' && github.ref_name == 'main'}}

        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Test
              run: echo hello

